// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Simple greeting command for demonstration purposes.
 */
async greet(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("greet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads user preferences from disk.
 * Returns default preferences if the file doesn't exist.
 */
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves user preferences to disk.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends a native system notification.
 * On mobile platforms, returns an error as notifications are not yet supported.
 */
async sendNativeNotification(title: string, body: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_native_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves emergency data to a JSON file for later recovery.
 * Validates filename and enforces a 10MB size limit.
 */
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads emergency data from a previously saved JSON file.
 * Returns FileNotFound if the file doesn't exist.
 */
async loadEmergencyData(filename: string) : Promise<Result<JsonValue, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_emergency_data", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes recovery files older than 7 days.
 * Returns the count of removed files.
 */
async cleanupOldRecoveryFiles() : Promise<Result<number, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Shows the quick pane window and makes it the key window (for keyboard input).
 */
async showQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismisses the quick pane window.
 * On macOS, resigns key window status before hiding to avoid activating main window.
 */
async dismissQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles the quick pane window visibility.
 */
async toggleQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the default shortcut constant for frontend use.
 */
async getDefaultQuickPaneShortcut() : Promise<string> {
    return await TAURI_INVOKE("get_default_quick_pane_shortcut");
},
/**
 * Updates the global shortcut for the quick pane.
 * Pass None to reset to default.
 */
async updateQuickPaneShortcut(shortcut: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_quick_pane_shortcut", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Initialize a Git repository for a project with proper directory structure.
 * 
 * Creates the following structure:
 * - context/ - for uploaded files
 * - decisions/ - for decision records
 * - experiments/ - for experiment results
 * - .gitattributes - LFS rules for PDF and Excel files
 * - README.md - initial project documentation
 */
async initializeGit(path: string) : Promise<Result<GitInitResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_git", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Detect if Git LFS is installed and available.
 * 
 * Returns true if `git-lfs version` command succeeds.
 */
async detectGitLfs() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_git_lfs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all files in a project directory recursively.
 * 
 * Filters for supported file types (CSV, PDF, XLSX, XLS) and returns
 * file metadata for display and selection.
 */
async listProjectFiles(projectPath: string) : Promise<Result<ProjectFile[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_project_files", { projectPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Upload a context file to the project.
 * 
 * Parses the file (CSV/PDF/Excel), copies it to the project's context directory,
 * and commits it to Git. Sends progress updates via channel.
 */
async uploadContextFile(path: string, projectId: string, onProgress: TAURI_CHANNEL<UploadProgress>) : Promise<Result<ContextFileRecord, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upload_context_file", { path, projectId, onProgress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Auto-commit files to Git repository with proper LFS handling.
 * 
 * LFS tracking is automatic via .gitattributes rules created during project init.
 * Files matching .gitattributes patterns (PDF, Excel >10MB) are automatically tracked by Git LFS.
 * 
 * # Arguments
 * * `repo_path` - Path to the Git repository
 * * `files` - List of file paths relative to repo root (e.g., "context/file.csv")
 * * `message` - Commit message
 * 
 * # Returns
 * The commit ID (SHA) as a string
 */
async gitAutoCommit(repoPath: string, files: string[], message: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_auto_commit", { repoPath, files, message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends a chat message to Claude API with streaming responses.
 * 
 * # Arguments
 * * `message` - The user's message
 * * `history` - Previous conversation messages
 * * `system_prompt` - Optional system prompt for context
 * * `channel` - Tauri channel for streaming token events
 * 
 * # Streaming Events
 * - `StreamEvent::Token { content }` - Each token as received
 * - `StreamEvent::Done` - Stream completed successfully
 * - `StreamEvent::Error { message }` - Error occurred during streaming
 * 
 * # Errors
 * Returns `ChatError` for API failures, configuration issues, or network errors.
 */
async sendChatMessage(message: string, history: ChatMessage[], systemPrompt: string | null, channel: TAURI_CHANNEL<StreamEvent>) : Promise<Result<ChatResponse, ChatError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_chat_message", { message, history, systemPrompt, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a decision log markdown file and commit it to Git.
 * 
 * # Arguments
 * * `content` - Markdown content with YAML frontmatter
 * * `filename` - Filename (e.g., "2026-02-04-investor-eval.md")
 * * `project_path` - Path to the project root (Git repository)
 * 
 * # Returns
 * The full relative path to the created file (e.g., "decisions/2026-02-04-investor-eval.md")
 */
async createDecisionLog(content: string, filename: string, projectPath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_decision_log", { content, filename, projectPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write an experiment config YAML file and commit it to Git.
 * 
 * # Arguments
 * * `project_path` - Path to the project root (Git repository)
 * * `filename` - Filename (e.g., "2026-02-06-seed-fundraising.yaml")
 * * `yaml_content` - YAML content to write
 * 
 * # Returns
 * The relative file path on success (e.g., "experiments/2026-02-06-seed-fundraising.yaml")
 */
async writeExperimentConfig(projectPath: string, filename: string, yamlContent: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_experiment_config", { projectPath, filename, yamlContent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read an experiment config YAML file from the experiments/ directory.
 * 
 * # Arguments
 * * `project_path` - Path to the project root (Git repository)
 * * `filename` - Filename (e.g., "2026-02-06-seed-fundraising.yaml")
 * 
 * # Returns
 * The YAML content as a string
 */
async readExperimentConfig(projectPath: string, filename: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_experiment_config", { projectPath, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application preferences that persist to disk.
 * Only contains settings that should be saved between sessions.
 */
export type AppPreferences = { theme: string; 
/**
 * Global shortcut for quick pane (e.g., "CommandOrControl+Shift+.")
 * If None, uses the default shortcut
 */
quick_pane_shortcut: string | null; 
/**
 * User's preferred language (e.g., "en", "es", "de")
 * If None, uses system locale detection
 */
language: string | null }
/**
 * Error types for chat operations
 */
export type ChatError = 
/**
 * API key not configured in environment
 */
{ type: "ConfigError"; message: string } | 
/**
 * Rate limit exceeded (429)
 */
{ type: "RateLimitError"; retry_after: number | null } | 
/**
 * API server error (5xx)
 */
{ type: "ApiError"; message: string } | 
/**
 * Request timeout
 */
{ type: "TimeoutError" } | 
/**
 * Network or HTTP error
 */
{ type: "NetworkError"; message: string } | 
/**
 * SSE parsing error
 */
{ type: "ParseError"; message: string }
/**
 * A single chat message in the conversation history
 */
export type ChatMessage = { role: string; content: string }
/**
 * Response from the chat command
 */
export type ChatResponse = { success: boolean }
/**
 * Record of an uploaded context file with parsed metadata.
 */
export type ContextFileRecord = { 
/**
 * Original filename as uploaded
 */
originalFilename: string; 
/**
 * Sanitized filename stored in project (slugified)
 */
storedFilename: string; 
/**
 * File type: "csv", "pdf", or "excel"
 */
fileType: string; 
/**
 * Detected data type based on content analysis (e.g., "customer_data")
 */
detectedType: string | null; 
/**
 * Number of rows (for CSV/Excel, excluding header)
 */
rows: number | null; 
/**
 * Column names (for CSV/Excel)
 */
columns: string[] | null; 
/**
 * Data preview for CSV/Excel (first 10 rows, max 500 chars)
 */
preview: string | null; 
/**
 * Number of pages (for PDF)
 */
pages: number | null; 
/**
 * Text preview for PDF (max 500 chars)
 */
textPreview: string | null; 
/**
 * File size in bytes
 */
sizeBytes: number; 
/**
 * Relative path in project (e.g., "context/file-2.csv")
 */
relativeFilePath: string; 
/**
 * Whether file exceeds LFS threshold (>10MB)
 */
isLfs: boolean }
/**
 * Result of Git initialization.
 */
export type GitInitResult = { success: boolean; path: string; lfsAvailable: boolean; commitHash: string | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Information about a file in the project directory.
 */
export type ProjectFile = { path: string; name: string; extension: string; size: number; isSupported: boolean }
/**
 * Error types for recovery operations (typed for frontend matching)
 */
export type RecoveryError = 
/**
 * File does not exist (expected case, not a failure)
 */
{ type: "FileNotFound" } | 
/**
 * Filename validation failed
 */
{ type: "ValidationError"; message: string } | 
/**
 * Data exceeds size limit
 */
{ type: "DataTooLarge"; max_bytes: number } | 
/**
 * File system read/write error
 */
{ type: "IoError"; message: string } | 
/**
 * JSON serialization/deserialization error
 */
{ type: "ParseError"; message: string }
/**
 * Progress event emitted during streaming
 */
export type StreamEvent = { type: "Token"; content: string } | { type: "Done" } | { type: "Error"; message: string }
export type TAURI_CHANNEL<TSend> = null
/**
 * Progress updates during file upload.
 */
export type UploadProgress = 
/**
 * Parsing file content
 */
{ type: "Parsing"; percent: number } | 
/**
 * Copying file to project
 */
{ type: "Copying"; percent: number } | 
/**
 * Committing to Git
 */
{ type: "Committing"; percent: number } | 
/**
 * Upload complete with file record
 */
{ type: "Complete"; record: ContextFileRecord } | 
/**
 * Error occurred
 */
{ type: "Error"; message: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
